# Generated by Django 3.1.1 on 2020-09-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('whatIs', models.CharField(max_length=1000)),
                ('yes', models.TextField(max_length=1000)),
                ('no', models.TextField(max_length=1000)),
            ],
        ),
    ]
