# Generated by Django 3.1.1 on 2020-09-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition',
            old_name='number',
            new_name='title',
        ),
    ]
