# Generated by Django 3.1.1 on 2020-09-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200909_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition',
            old_name='title',
            new_name='number',
        ),
    ]
