# Generated by Django 3.1.1 on 2020-09-10 22:37

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_proposition_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='color',
            field=colorfield.fields.ColorField(default='#808080', max_length=18),
        ),
    ]
